version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: plant_postgres
    environment:
      POSTGRES_USER: plant_user
      POSTGRES_PASSWORD: plant_pass
      POSTGRES_DB: plant_local
    ports:
      - "5432:5432"
    volumes:
      - plant_pgdata:/var/lib/postgresql/data

volumes:
  plant_pgdata:
